### ISSUE TITLE
Any kind of error from query kills the Think hook

### ISSUE THREAD

**Issue by wyozi** [Meow/gmsv_pg#2]
I'm not sure if that's what you referred to by `Most of the functions are able to throw Lua errors in case of bad input. Be careful!`, but this seems quite inconvenient especially during development. Any chance of wrapping it in a pcall or something to not kill IO?

It's not just syntax errors it happens for, but constraint violations etc too.

**Comment by Meow** [comment]
Thanks for reporting the issue. I'll look into it as soon as I can (which is - nearest weekend), in the meantime you can provide an example of the code that is causing issues so that I can nail down the issue faster.

**Comment by wyozi** [comment]
Here's a small repro I tested with

```lua
require "pg"

local host, username, password, database, port = ...

local db = pg.new_connection()
local status, err = db:connect(host, username, password, database, port)

print(status, err)

local q = db:query("SELECT '1")
q:on("success", print)
q:on("error", print)

q:run()
```

Running it three times gives this output:
```
lua_openscript epic.lua
Running script epic.lua...
true    nil
ERROR:  unterminated quoted string at or near "'1"
LINE 1: SELECT '1
               ^

lua_openscript epic.lua
Running script epic.lua...
true    nil
lua_openscript epic.lua
Running script epic.lua...
true    nil
```

You can see the error during the first run but on subsequent runs no callbacks get called. This also happens to constraint violations etc, but syntax error was easy to test with locally.

**Comment by Meow** [comment]
Thanks, I'll look into it as soon as I can!

**Comment by wyozi** [comment]
@Meow thanks for the fix! I've been using the module with a workaround for the async response problem for a week now and everything else seems to be working fine :+1:

**Comment by Meow** [comment]
@wyozi I'm glad to see someone use my module :)
And you're welcome. Thanks for reporting the issue!
