### ISSUE TITLE
Think hook for async queries does not get added

### ISSUE THREAD

**Issue by wyozi** [Meow/gmsv_pg#3]
First of all apologies for really bad repro, I'll add more details once I get them. Basically when using `q:set_sync(false)`, the `Think` hook does not seem to get added to gmod hook list, so the callbacks never end up getting called.

Here's a code I tried with

```lua
print(pg.version)
local q = pgdb:query("SELECT 1")
print(q:set_sync(false))
print(q:on("success", print))
print(q:on("error", print))
PrintTable(hook.GetTable().Think)
```
with output
```
[13:45] 1.0.0-experimental
[13:45] no value
[13:45] no value
[13:45] no value
[13:45] (list of hooks none of which is from gmsv_pg)
```

If I read the source code correctly, in any case the Think hook should exist at this point no matter what threading problems or other weird stuff there might have happened in the background, right? I'll see if  I can get more details.

**Comment by Meow** [comment]
You need to have at least 1 player on the server (or a bot) for the Think hooks to work. Also Query#on doesn't return anything as far as I know.

Here is an example of the correct usage with sync on:
```lua
    query_obj:set_sync(true)
    local success, res, size = query_obj:run()
```

And with sync off (assuming at least one player is on the server):
```lua
  query_obj:on("success", ...)
  query_obj:on("error", ...)
  query_obj:run()
```

**Comment by wyozi** [comment]
It's not a problem with using the API/Think hook not getting called. It's a problem with the `Think` hook not getting added to Garry's Mod's list of hooks at all, meaning that there is no way the callback can get called since nothing is getting run from gmsv_pg on the main Lua event loop.

Printing return values of the functions was just to make sure there is no weird errors/other garbage being thrown into the Lua state.

**Comment by Meow** [comment]
![3zyjwvw](https://user-images.githubusercontent.com/1764448/52164733-5b795780-26f6-11e9-87f8-c091c12e7352.png)
Just tried it myself

**Comment by wyozi** [comment]
This is something I should have definitely emphasized in the first post, but that is the whole problem: it should add the hook but it does not, and I'm not sure why this is happening. There is a possibility that it is related to some ulx fuckery and the hook does not get added properly or gets removed abruptly, but I doubt that this is the case. These are the details I've still yet to figure out on my testing environment.

I think this is quite dependent on the internal workings of the library. When does the hook actually get added to the gmod context? I was under impression that `DatabaseQuery::Make` creates a new instance, and thus should add the hook immediately upon call to `query#on`. This would not be the case if there some kind of internal pool from which `DatabaseQuery` is retrieved, in which case the hook could have been added earlier, setting the `_hooked` property to true. Mostly asking about these so I can better try to debug the problem on my side.

**Comment by Meow** [comment]
According to gloo source code the hook is added whenever the `addListener` is called, so it should add it as soon as query#on or query#once is called.

**Comment by wyozi** [comment]
I'll try to reproduce the problem in local environment. Right now I'm testing things on a real server, which uses quite a lot of `set_sync(true)` still, so that might affect the behavior.

**Comment by Meow** [comment]
My own project, which uses this module, also uses the sync mode a lot during the boot phases. You can check out my own usage of it here:
https://github.com/TeslaCloud/Flux/blob/master/garrysmod/gamemodes/flux/gamemode/lib/active_record/adapters/pg.lua

As well as throughout the files (which use the abstracted query engine):
https://github.com/TeslaCloud/Flux/tree/master/garrysmod/gamemodes/flux/gamemode/lib/active_record

also
https://github.com/TeslaCloud/Flux/blob/master/garrysmod/gamemodes/flux/gamemode/lib/active_record/adapters/abstract.lua#L101

**Comment by wyozi** [comment]
There's a possibility that the problem is related to the OS, since the the problem only happens on srcds that runs on Ubuntu. I'll try again later if I can get the server to a state where the problem would happen.

**Comment by Meow** [comment]
The module is compiled and tested on a Debian 9 machine. It was also tested to run okay in the production conditions (also Debian 9). I'll investigate if it's caused by the OS when I can.

**Comment by wyozi** [comment]
After a server restart the hook gets added properly for now. I think the issue _may_ be related to the fact that the server was not restarted between running code that caused the thread to die as per issue #2 and updating the binary to the new version of the library. This could have somehow caused the static map of Lua states ->LuaEventEmitterManagers to refer to the outdated class instance (???).

I'm still not 100% sure the issue won't happen again, but if the hook is still there tomorrow or so, I'll close the issue.

**Comment by wyozi** [comment]
I don't think anything related to this specific issue broke, so I'm closing the issue now
