### ISSUE TITLE
How's the binary built?

### ISSUE THREAD

**Issue by wyozi** [Meow/gmsv_pg#6]
This might just be me doing something stupid, but I cannot get the compiled binary for Linux to work properly. I made a fork of the library (https://github.com/wyozi-gmod/gmsv_pg) which compiles and works well on Windows, but the linux build keeps printing `Couldn't load module library!`, which I think is somehow related to the `pq` dependency. If you could describe the way you build the binary for Linux, that would be helpful.

**Comment by wyozi** [comment]
I think the problem is in different dependencies on the binaries:

Compiling master branch by myself:
```
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux.so.2]
```

Downloading the binary from releases:
```
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libpq.so.5]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux.so.2]
```

Not sure how to fix this

**Comment by wyozi** [comment]
Okay, adding `--no-as-needed` to linker flags fixed this. Apparently some Ubuntu thing..

**Comment by Meow** [comment]
The binary was built on Debian 9 using gcc that comes with it. It was ensured to compile right out of the box since I am using semi-automated build pipelines for releases.
```
premake5
make
```

**Comment by wyozi** [comment]
Hmm, it's interesting that the linker thinks some of the symbols from libpq aren't used.
